### PR TITLE
Use embeds for reports

### PR DESCRIPTION
**Pull request by cntkillme**
Introduces a timestamp, removes newlines and unnecessary whitespace automatically, and prevents mentions from users in the report reason.

### CODE REVIEW

**Comment by cntkillme** [comment]
Potential issue: embed value limit

**Comment by TinyPandas** [comment]
Are we looking to implement a front-end solution to this?

Are we going to utilize HTML files as suggested by @M39a9am3R?

If neither of the above, or postponed implementations, we can resort to either paged results, or something similar to Sentry where it would auto break the results after so many character. We would just have to do it better, in the sense that if the next result would go past the limit, it would be added to the next message instead of breaking it up across two.

**Comment by cntkillme** [comment]
An HTML file is probably the best bet, it can including searching, sorting, and other things that might be useful.

**Comment by TinyPandas** [comment]
Sure, an HTML file might be better. An issue I could see moving forward, if it is bot specific, we would need someway to "serve" the files if we wanted them interlinked. Also to save space on the bot side of things, we would have to update the files each time we used a history / `getInfraction` command, this way it updates the file instead of creating a new one.

**Comment by cntkillme** [comment]
To be clear, this currently only amends the report command and has nothing to do with the report history. I think embeds are safe enough here, we can cut off the reason if it is too long anyways-- they shouldn't be more than a few dozen to a hundred characters anyways I think.

**Comment by TinyPandas** [comment]
Oh, if it's just the reason, then embeds will be more than enough. I doubt there will be any reason longer than 1k characters.

**Pull request merged**
